Hubs-Foundation/reticulum

lib/ret_web/controllers/page_controller.ex, lib/ret_web/endpoint.ex, lib/ret_web/templates/page/hub-meta.html.eex
This makes an attempt at inlining proper META tags at the top of the hub landing page so it will unfurl reasonably.
Goes with https://github.com/mozilla/hubs/pull/281
=> Add meta tags for hubs

lib/ret_web/plugs/redirect_to_main_domain.ex, lib/ret_web/router.ex
This adds a phoenix plug to ensure we always redirect users to the production domain
=> Redirect to moz.com from moz.org

scripts/build.sh
This directory was not created when rebuilding the reticulum box. We now ensure the directory is created when running the build script.
=> Create priv/static/ directory if it doesn't exist.

config/config.exs
I think this was a typo back when it was added in https://github.com/mozilla/socialmr/commit/857a6f84c244f738c4b0471ed725833232a27fa2#diff-1b1ba7f7894ccf1a0c686635b9d5b942R12
Not sure if this has actually affected anything.
=> Fix typo: Posion->Poison

lib/ret_web/controllers/api/v1/media_controller.ex, lib/ret_web/views/api/v1/media_view.ex
Adds the ability to pass an optional "index" to the farspark URL generator API, and also returns URLs for extracting frames/pages via index (as either PNG or JPG)
=> Allow passing index, add extract return values

config/dev.exs, lib/ret/page_origin_warmer.ex, lib/ret_web/controllers/page_controller.ex, scripts/build.sh
After this PR, we should neither fetch nor try to use any of the smoke-prefixed pages from S3 in Reticulum, which is great because we had no reason to.
=> Stop using smoke- pages

lib/ret/uploads.ex, lib/ret_web/controllers/api/v1/media_controller.ex
This PR updates the reticulum media API to try to extract the mime type from the uploaded file path if the browser did not specify a content type.
=> Recognize MIME type based upon path for uploads

lib/ret/uploads.ex
This tiny PR removes storage of the original filename in the meta file for uploads, because we don't need it and it may contain private information.
=> Don't store the filename in the meta file

lib/ret/media_resolver.ex
This flips us from a whitelist to a blacklist of domains to route through YT-DL.
=> Route most URLs through yt-dl

lib/ret_web/channels/hub_channel.ex, lib/ret_web/controllers/api/v1/scene_controller.ex, test/ret/storage_test.exs, test/ret_web/controllers/api/scene_controller_test.exs, test/support/conn_case.ex, test/support/test_helpers.ex
Before this PR it was possible to mutate a scene regardless of what account you were logged in as (oops.) As part of this I added a test suite for the scene controller.
=> Fix scene mutation security issue

lib/ret/hub.ex, lib/ret/sids.ex, lib/ret_web/controllers/page_controller.ex
This PR tries to put things in a bit of a saner place wrt sids and permalinks. The goal is to:
- Enable permalinks via hub.link
- Keep them relatively short
Currently, the invite dialog in the client shares `hub.link/entry code` links, which unintuitively expire after 24h. It seems like a good idea to just use entry codes for the case of "go to hub.link directly, type in entry code" since having those expire is OK since it's likely you are getting that information verbally or due to an immediate need, whereas any URL we share ideally should not expire (unless the user wants it to, which is something we may add later.)
This PR:
- Changes the sid generation to 7 alphanumeric chars for a keyspace of 78364164096. (This may not be enough in the long run, but for now is probably fine given the …
=> Short permalinks

lib/ret/web_push_subscription.ex, lib/ret_web/channels/hub_channel.ex
This updates the push API support in reticulum:
- Joining a hub channel now expects an optional web push subscription endpoint, and if supplied will return a flag in the response if there is a subscription for the hub channel being joined for that endpoint
- The `unsubscribe` channel message now provides a response which will tell the caller if the endpoint being unsubscribed has any remaining subscriptions
=> Update API for new push client changes

lib/ret/scene.ex, lib/ret_web/views/api/v1/scene_view.ex
This PR updates the attributions to be structured JSON data, which will be passed in from spoke to include the individual content attributions (which will have the origin url, name, and author)
See also https://github.com/MozillaReality/Spoke/pull/358 https://github.com/mozilla/hubs/pull/664
=> Add new attributions to schema

lib/ret_web/channels/hub_channel.ex
Fix for https://sentry.prod.mozaws.net/operations/reticulum/issues/4924667/?query=is:unresolved which was causing a match error when a bad hub sid was passed into join
=> Push entry code update after filtering for nil

lib/ret/media_resolver.ex, lib/ret_web/controllers/api/v1/media_controller.ex, lib/ret_web/views/api/v1/media_view.ex
**Don't merge quite yet, relies on correct `image/*` handling on the client.**
Whenever we return a content type it saves us a round trip on the client to go see what is there, so we should do it whenever we can.
Also fixed up the imgur handling, which was making an extra API request to get out imgur media URLs which were already present in the original API response; and removed obsolete Farspark-URL-generating machinery.
=> Emit more content types from Reticulum, small cleanup

lib/ret/media_resolver.ex, lib/ret_web/controllers/api/v1/media_controller.ex, mix.exs, mix.lock
This updates the MediaResolver to be parameterized on a struct, and adds user agent detection for Safari to force mp4 as the desired file format.
=> Check user agent for Safari to disable webm support

lib/ret/enums.ex, lib/ret_web/templates/page/scene-meta.html.eex, lib/ret_web/views/api/v1/scene_view.ex, priv/repo/migrations/20190312171503_add_removed_state_to_scenes.exs
Adds the `removed` enum state to scenes, and now masks out all places where we return scene information in the API if the scene (or listing) has been taken down.
=> Handle removed scenes, add removed scene enum

lib/ret/avatar.ex, lib/ret/storage.ex, lib/ret_web/controllers/api/v1/avatar_controller.ex
When updating an avatar files that are `null` in the request will correctly be unassociated with the avatar record.
=> Add ability to remvoe maps from avatars

lib/ret_web/channels/hub_channel.ex
This is sort of redundant for our client, since the pinnage is also communicated via a NAF update on the `pinnable` component. However, it's necessary in order for our Discord bot, which doesn't receive unreliable NAF messages, to know about pins.
In theory, this could probably be fixed more cleanly (in some sense) by making the NAF component update reliable, or by making the Discord bot subscribe to the Janus data channel, but both of those are so much more of a PITA in our architecture that this seems like the best solution.
=> Broadcast successful pins to clients

lib/ret/hub.ex
It doesn't seem like there is any reason for these, and obviously it is nice to put all of the rest of the characters into Hubs names.
In addition, it's painful to have any reason why Reticulum rejects hub creations or renames, since if you make a request and the name you submitted is invalid you will either get (in the case of creations) a meaningless and hard-to-guess-why-it-happened error message back or (in the case of renames) radio silence. So until that's fixed it's nice to minimize how often that happens.
=> Greatly loosen hub name restrictions

lib/ret/avatar.ex, lib/ret_web/views/api/v1/avatar_view.ex
When setting multiple maps at once on an avatar only the last map would actually apply because the wrong changeset was being carried forward. This regressed when adding the ability to remove maps.
Also adds `gltf_url` to the response for an avatar which points at the reticulum endpoint for the generated skinned avatar, with a query param for cachebusting based on the `updated_at` column. We should eventually return a CDN cached url for this.
=> Fix setting multiple avatar maps at once and add cachebusting url to avatar response

lib/ret_web/controllers/api/v1/media_controller.ex
Fixes a bug where we were not properly returning farspark paginating URLs for PDF uploads.
=> Properly render farspark urls for pdf uploads

lib/ret_web/channels/hub_channel.ex, test/ret/hub_test.exs
Adds the `mute` message for user soft muting, which requires `mute_users` permission to deliver to the specific session.
=> Add mute message

lib/ret/asset.ex, lib/ret/project.ex, lib/ret_web.ex, lib/ret_web/controllers/api/v1/assets_controller.ex, lib/ret_web/controllers/api/v1/project_assets_controller.ex, lib/ret_web/controllers/api/v1/project_controller.ex, lib/ret_web/controllers/controller_helpers.ex, lib/ret_web/router.ex, lib/ret_web/views/api/v1/asset_view.ex, lib/ret_web/views/error_view.ex, test/ret_web/controllers/api/assets_controller_test.exs, test/ret_web/controllers/api/project_assets_controller_test.exs, test/ret_web/controllers/api/projects_controller_test.exs, test/support/test_helpers.ex
- Added POST `/api/v1/assets` route which creates a new user owned asset and accepts an owned file id and access token
- Added DELETE`/api/v1/assets/:id` route which deletes a user owned asset and all ProjectAsset relations
- Added DELETE `/api/v1/projects/:id` for deleting a project
- Added an additional POST `/api/v1/projects/:project_id/assets` route for adding an existing asset to a project by creating a ProjectAsset relation
- Added DELETE `/api/v1/projects/:project_id/assets/:id` for removing an asset from a project by deleting the ProjectAsset relation
=> New Asset, Project, and ProjectAsset routes

lib/ret/project.ex, test/ret_web/controllers/api/projects_controller_test.exs
Fixed a nasty bug in Spoke where projects were being overwritten because the project show path was returning a null project url.
=> Preload project and thumb files

lib/ret/discord_client.ex, lib/ret/hub_binding.ex, lib/ret_web/channels/hub_channel.ex
Based on #152. Overrides presence updates with display names from Discord.
=> Override prescence with discord identity

lib/ret_web/controllers/api/v1/avatar_controller.ex, lib/ret_web/router.ex, lib/ret_web/views/api/v1/avatar_view.ex
This is a version of the avatar with none of the local texture overrides applied, which is used in the client as the basis for preview (so that clearing maps can be previewed correctly)
=> Add base_gltf_url to avatar to support preview

lib/ret/hub.ex, lib/ret_web/channels/hub_channel.ex, lib/ret_web/controllers/api/v1/hub_controller.ex, lib/ret_web/views/api/v1/hub_view.ex, test/ret/hub_test.exs, test/ret_web/controllers/api/projects_controller_test.exs
Adds the ability to close a hub if you have owner permissions.
Also updates `join_hub` permission to be denied to all users when the hub's `entry_mode`' is `deny`.
I carved out a new permission for this, vs using `update_hub` permission -- somewhat subjective but it felt like this could theoretically be conferred to different roles in the future. (Eg a community member running an event may be able to rename the room or change the scene, but not be allowed to shut down the room, which is destructive.)
Goes with https://github.com/mozilla/hubs/pull/1260
=> Add close_hub permission and verbs

lib/ret/project.ex, lib/ret_web/controllers/api/v1/project_controller.ex, test/ret_web/controllers/api/projects_controller_test.exs
The project create route doesn't allow you to specify the project file or thumbnail file. This PR adds support for those parameters. This is a breaking change for Spoke and should be merged along with the [Spoke onboarding branch](https://github.com/MozillaReality/Spoke/pull/501/)
=> Make the project create route take additional parameters

lib/ret/avatar.ex, lib/ret/media_search.ex, lib/ret_web/controllers/api/v1/media_search_controller.ex, lib/ret_web/views/api/v1/avatar_view.ex, priv/repo/migrations/20190424010558_add_thumbnail_to_avatar.exs, test/ret_web/controllers/api/media_search_controller_test.exs, test/support/test_helpers.ex
Adds a thumbnail owned file to avatar records and an "avatars" source to the search API. The avatars source currently only supports returning results by user. Also, the only user you are currently authorized to search for is the one you are authenticated as.
todo:
=> Avatar search and thumbnails

lib/ret_web/channels/auth_channel.ex, lib/ret_web/channels/link_channel.ex, lib/ret_web/channels/ret_channel.ex
Add session id in join responses for all channels, in part to fix link codes. Goes with https://github.com/mozilla/hubs/pull/1304
=> Return session id for link codes

lib/ret/avatar.ex, lib/ret/avatar_listing.ex, lib/ret/enums.ex, lib/ret/media_search.ex, lib/ret_web/controllers/api/v1/avatar_controller.ex, lib/ret_web/controllers/api/v1/media_search_controller.ex, lib/ret_web/router.ex, lib/ret_web/views/api/v1/avatar_view.ex, priv/repo/migrations/20190501221754_create_avatar_listings.exs, priv/repo/migrations/20190508021811_update_avatar_constraints.exs
This PR adds the AvatarListings model as and updates the Avatars model to support listings (with the reviewed_at and parent_avatar_listing fields).
It also expands the functionality of the AvatarController to support setting the other avatar fields (description, allow_promotion, parent_avatar_listing, etc) as well as deleting avatars.
The plan is to push this out along with the admin panel for avatars, set up the base bot as a AvatarListing, and then make a PR to update existing avatars pointing at the base bot avatar to point at the base bot avatar listing instead, using it for cascading instead of parent_avatar when available.
=> Avatar listings

lib/ret/hub.ex, priv/repo/migrations/20190514175300_add_last_active_at.exs
Our KPI we want to track is monthly active rooms, which was not possible to do accurately without keeping a timestamp of the last time a room became active.
=> Add last active at telemetry

lib/ret/discord_client.ex, lib/ret/hub_binding.ex, lib/ret_web/channels/hub_channel.ex
- Discord displayNames no longer contain the discriminator number
- We also now lookup the server-specific "nickname" and use that if available
- Injects a new communityIdentifier field into the presence profile that includes the discord discriminator
=> Friendly display name

lib/ret/avatar.ex, lib/ret/avatar_listing.ex, lib/ret/enums.ex, lib/ret/media_search.ex, lib/ret_web/controllers/api/v1/avatar_controller.ex, lib/ret_web/router.ex, lib/ret_web/views/api/v1/avatar_view.ex
This adds endpoinds for avatar listings similar to how we handle scenes/scene_listings. `/ap1/v1/avatars` can now take either and avatar or avatar listing sid (yuck, but keeping it consistent with scenes for now).
This PR also adds support for using an avatar listing as a parent avatar, and simplifies the semantics of the collapsing behavior to only support a single level of parenting.
=> Endpoints for Avatar Listings

lib/ret/avatar_listing.ex, lib/ret/oauth_token.ex, lib/ret_web/controllers/api/v1/oauth_controller.ex
Fixes a couple of errors caught by sentry.
- Handle expired oauth tokens
- Handle denied oauth
- Extend oauth token expiry from 5 minutes to 10 minutes
=> OAuth error handling

lib/ret/sids.ex
Add `1Il` and `O0` to list of undesirable characters, since they are hard to distinguish in most fonts. This also changes the algorithm to draw from a longer list of crypto random characters, instead of simply replacing characters with random digits.
=> Remove characters from sids that are difficult to distinguish

lib/ret/avatar.ex, lib/ret_web/controllers/page_controller.ex, lib/ret_web/templates/page/avatar-meta.html.eex
Adds routes + meta for avatar landing pages. Avatar responses now point to these pages in their `url` property.
=> Add Avatar landing pages

config/dev.exs
Fixes up reticulum to run on a local LAN IP (you need to now change one line of `dev.exs`)
Goes with https://github.com/mozilla/hubs/pull/1455
=> Fix up local IP case

lib/ret/crypto.ex, lib/ret/login_token.ex, lib/ret_web/channels/auth_channel.ex, priv/repo/migrations/20190703224946_add_login_token_payload_keys.exs, test/ret/login_token_test.exs
Goes with https://github.com/mozilla/hubs/pull/1496
This rolls back the change in https://github.com/mozilla/reticulum/pull/194 because it failed to address signing in from PWAs. The reason is because when using a PWA, the opposite auth channel connection is closed before it could respond with the email address.
This new approach stores a secret symmetric key with the login token, and encrypts the email with the key and puts it into one of the query string variables of the sign in link. This encrypted payload is then handed to the auth channel on the verification side and the secret symmetric key is used to decrypt and broadcast the email address to all on the channel.
This seemed like a better approach than putting the email address in the query string directly (obviously) or putting a …
=> Fix for PWA signin v2

config/dev.exs, habitat/config/config.toml, lib/ret_web/controllers/api/v1/media_controller.ex, lib/ret_web/views/api/v1/media_view.ex
Removes the `raw` field from media resolver results (dependent upon https://github.com/mozilla/hubs/pull/1595) -- and hence drops references to `farspark` from reticulum.
Also, adds a necessary CSP rule for PDF conversion.
=> Remove farspark, update CSP

lib/ret/media_resolver.ex
This fixes query parameter encoding when making the API request to youtube-dl-server. It also ignores unknown video formats (which also includes redirects for some reason).
Fixes https://github.com/mozilla/Spoke/issues/689
=> Fix query parameter encoding for youtube-dl-server

Jenkinsfile
As far as I can tell, this line in the Jenkinsfile is what's causing the build to happen on non-master branches.
I'm not sure it's necessary, since the configuration on the Jenkins job already takes care of SCM tasks
=> Remove scm step from jenkinsfile

lib/ret/avatar.ex, lib/ret/avatar_listing.ex, lib/ret/scene.ex, lib/ret/scene_listing.ex, test/ret_web/controllers/api/scene_controller_test.exs
Our slug code in `Hub` properly ignored uniqueness of slugs and also updates the slug when the room changes. We weren't doing this for the other entities which have slugs: avatars, avatar listings, scenes, and scene listings. This PR rectifies that.
(Slugs do not need to be unique nor should they be immutable, since they are not the unique identifiers in our system, the SID is, and they are used just to adorn the URL with information.)
=> Drop uniqueness on slugs and always update them

lib/ret_web/channels/hub_channel.ex, scripts/start.sh
Adds support for two new reticulum events which update presence state so that the client can know which users are currently going through the entry flow. This is used to enforce a soft cap on room capacity.
=> Add entering presence

lib/ret/avatar.ex, lib/ret/avatar_listing.ex, lib/ret/crypto.ex, lib/ret/enums.ex, lib/ret/gltf_utils.ex, lib/ret/media_search.ex, lib/ret/storage.ex, lib/ret_web/controllers/api/v1/avatar_controller.ex, lib/ret_web/controllers/api/v1/media_search_controller.ex, lib/ret_web/views/api/v1/avatar_view.ex, priv/repo/migrations/20190812211919_add_avatar_listings_account.exs, priv/repo/migrations/20190819204535_add_avatar_listings_removed_state.exs, test/ret/avatar_listing_test.exs, test/ret/gltf_utils_test.exs, test/support/test_helpers.ex
This contains the necessary backend bits to turn on avatar remixing, namely:
- Allowing duplication of thumbnails when creating an avatar with a `parent_avatar_listing_id`
- Allow searching `avatar_listings` by tag, primarily for base, to be used in
the updated avatar picker and default to be used to remove client baked-in
avatars
- Bake account `into avatar_listings` instead of associating through avatars. When
deleting avatars also delist their associated listings, keeping the account
association for use down the road.
- Rework GLTF material resolving to have a traversal based fallback for finding
skinnable material.
TODO:
Decided to have the client handle renaming materials if a valid one is not found. The plan is to transition this to some meta information in the gltf eventually, but …
=> Avatar Remixing

lib/ret/page_origin_warmer.ex, lib/ret_web/controllers/page_controller.ex, lib/ret_web/templates/page/hub-meta.html.eex, lib/ret_web/templates/page/index-meta.html.eex, lib/ret_web/templates/page/scene-meta.html.eex
Fixes the iOS add to home icons and disables serving the manifest on iOS since webrtc won't work.
=> Disable PWA on iOS, fix icons

lib/ret/scene.ex
Previously we were updating the id directly rather than doing it through the association. I "fixed" this in my last PR but did not update the model to allow updates, so re-publishing scenes regressed.
=> Allow scene owned files to be updated

lib/ret_web/endpoint.ex, lib/ret_web/plugs/add_vary.ex
Hubs started loading photos before fetching them via XHR without an Origin header for some reason, and this results in Chrome mis-reading the non CORS'd responses from cache when we do make the XHR request to fetch the data. We should be returning "Vary: Origin" in the response from reticulum to ensure that browsers do not cache CORS and non-CORS responses.  See also: https://serverfault.com/questions/856904/chrome-s3-cloudfront-no-access-control-allow-origin-header-on-initial-xhr-req
=> Add Vary: Origin header to fix issues with chrome mis-caching

lib/ret_web/controllers/api/v1/media_controller.ex
`desired_content_type` was being thrown on the ground for non video uploads, this allows it to be passed through, falling back to the content type from Plug.Upload if it is not specified.
=> Respect desired_conent_type for non video uploads

lib/ret/media_search.ex, lib/ret_web/controllers/api/v1/media_search_controller.ex
The current "algorithm" is super simple and just returns avatars with the same `parent_avatar_listing_id` as the avatar sid specified. An immediate improvement would be to include anything with a shared ancestor, but the query for that is a bit trickier to write, so starting with this. Over time this could actually use some sort of more interesting metric of similarity.
=> "Similar to" search for avatar listings

lib/ret_web/endpoint.ex
Updates the origin check on the websocket to now properly use the `allowed_origins` config variable, which is now possible in Phoenix 1.4 since `origin_check` can point to a function evaluated at check time.
=> Add proper origin check to websocket

lib/ret/scene_listing.ex, lib/ret_web/controllers/api/v1/hub_controller.ex
Randomly selects a scene tagged 'default' when creating a hub when scene is unspecified.
=> Add default scene selection

README.md, config/dev.exs, config/prod.exs, habitat/config/config.toml, habitat/hooks/run, lib/ret/app_config.ex, lib/ret/application.ex, lib/ret/jobs/stats_job.ex, lib/ret/load_balancing/janus_load_status.ex, lib/ret/locking.ex, lib/ret/page_origin_warmer.ex, lib/ret/release_tasks.ex, lib/ret_web/controllers/health_controller.ex, lib/ret_web/controllers/page_controller.ex, lib/ret_web/plugs/redirect_to_main_domain.ex, priv/repo/migrations/20180408231444_create_session_stats_table.exs
In order to minimize AWS costs we need to ensure the database is completely disconnected from when the service is not in-use. To do so, we now run pgbouncer on each reticulum node for polycosm hosts, which serves as a connection pooler, and connect reticulum to pgbouncer over localhost. The reason being that pgbouncer will gracefully disconnect from the database if no transactions are being run if you use `transaction` scoped pooling. This is not possible to do natively in ecto -- ecto will just hold the connections open permanently while phoenix is running.
So the net goal of this PR is to a) deal with any issues stemming from the use of pgbouncer and b) remove all background jobs that would normally otherwise hit the database.
- First, pgbouncer's `transaction` scoped connection pooling …
=> Remove idle database accesses

lib/ret/media_search.ex
There are a few models in the Sketchfab collections I'd like to feature that are over the filesize / polycount limit. Because we check everything that goes into these collections, I think it's fine to increase these limits to a reasonably large upper bound.
=> Increase maximum sketchfab collection file size / polycount

assets/static/robots.txt, config/dev.exs, habitat/config/config.toml, habitat/default.toml, lib/ret_web/controllers/page_controller.ex, lib/ret_web/endpoint.ex, lib/ret_web/templates/page/robots.txt.eex, priv/static/robots.txt
Adds the ability to disallow crawlers, which will serve up a robots.txt denying all crawling other than twitter or facebook image unfurling bots.
Note this will be off by default in `ita` for self hosted instances.
=> Add dynamic robots.txt

lib/ret/avatar.ex, lib/ret/media_search.ex, lib/ret/project.ex, lib/ret/scene.ex, lib/ret/scene_listing.ex, lib/ret_web/controllers/api/v1/media_search_controller.ex, lib/ret_web/controllers/api/v1/project_controller.ex, lib/ret_web/controllers/api/v1/scene_controller.ex, lib/ret_web/router.ex, lib/ret_web/views/api/v1/hub_view.ex, lib/ret_web/views/api/v1/project_view.ex, lib/ret_web/views/api/v1/scene_view.ex, priv/repo/migrations/20191111234010_add_parenting_to_scenes.exs, priv/repo/migrations/20191121222742_add_parent_to_projects.exs, test/ret_web/controllers/api/projects_controller_test.exs, test/support/test_helpers.ex
This adds the ability to clone a scene or scene listing into "my scenes". A project is also created for the scene, though we may want to split that off into its own step.
To make creating publishing projects simpler, a new `/projects/:id/publish` endpoint has been added that will automatically create a scene if one does not exist and associate it with the project, then update its files, all in a single transaction.
Changes were also made to the responses for Scenes, SceneListings, and Projects ass well as the associated media search responses to facilitate the new client features this was built for.
Also small side fix for importing attributions from remote scenes/avatars.
=> Scene Remixing and Project publish endpoint

lib/ret/media_search.ex, lib/ret/project.ex, lib/ret/scene.ex, lib/ret/scene_listing.ex, lib/ret_web/channels/hub_channel.ex, lib/ret_web/controllers/api/v1/project_controller.ex
Fix scene preload issues introduced from scene remixing change, and centralize them so that we are less likely to break them in the future.
=> Fix scene preloads

config/dev.exs, lib/ret/discord_client.ex, lib/ret_web/controllers/page_controller.ex, lib/ret_web/views/api/v1/project_view.ex, test/ret/discord_client_test.exs
- Fix permissions overwrite in discord client
- Output newlines consistently in page_controller. We were only formatting page chunks with newlines on certain pages. This caused the google analytics script CSP to be correct on most pages, but incorrect on the link page. This changes the page controller to output newlines on all pages, which will require a new CSP SHA for the GA script.
=> Discord and CSP fixes

config/dev.exs, config/prod.exs, habitat/config/config.toml, lib/ret/locking.ex
It turned out that on AWS we don't want to force SSL, because in the self hosted case pgbouncer (communicating over localhost) is fine to be in the clear (and it'd be more complex to set up TLS over localhost, so not worth it.)
So this PR exposes `ssl` as a configuration value, off by default, when communicating with the database.
=> Disable SSL by default, make it configurable

config/dev.exs, habitat/config/config.toml, lib/ret_web/controllers/page_controller.ex
Drop the idea of proxying docs which seems like a bad idea due to security risk. Start serving docs directly.
=> Serve docs directly

lib/ret/media_search.ex
Does the same thing as https://github.com/mozilla/reticulum/pull/290 but for remixable scene listing search.
=> Preload project in remixable scene listing search

config/config.exs
Fixes an issue where JSON response from reticulum are having their Content-Type set to `application.vnd.pgrst.object+json`
=> Properly return json responses as application/json

lib/ret/support.ex
Properly disables slack notifications if the configuration value is empty.
=> Fix issue with slack notifications

lib/ret/cached_file.ex, lib/ret/media_resolver.ex, lib/ret_web/controllers/api/v1/media_controller.ex
Adds an optional `version` to the media resolver, which can be bumped to force the resolver to re-resolve + re-fetch the underlying assets.
=> Add URL versioning

lib/ret/media_resolver.ex, lib/ret_web/controllers/api/v1/media_controller.ex, lib/ret_web/views/api/v1/media_view.ex
Updates the media resolver to properly deal with youtube 360 videos. Particularly:
- Changes the boolean `low_resolution` flag to now be a `quality` measure, which can be `low`, `high`, `low_360`, or `high_360`
- Updates the API so the client now can specify quality, instead of deriving it from the user agent
- `low_360` and `high_360` now perform two `youtube-dl` requests in order to extract the video and audio streams separately. this is done because it was determined that youtube serves these up separately for 360 videos, there is no way to get an all-in-one stream.
- if there's a separate audio stream, it is returned in `origin_audio`
- deals with a change in youtube where you can't get equirectangular 360 videos unless you pass an empty user-agent string (youtube dl server has been …
=> Improve Quality of 360 Youtube Videos

lib/ret_web/controllers/page_controller.ex, mix.lock
Fixes issues with resolving short links on client because we were not handling redirects properly in reticulum-based cors proxy and were not including the proper HTTP headers in responses.
=> Add proper hub headers to link pages

lib/ret/hub.ex, lib/ret_web/controllers/page_controller.ex
Adds caching to the "default room" check on the index page, and a null check for `allow_promotion` on room settings API (for backwards compat).
=> Quick fixes to public rooms PR

lib/ret_web/email.ex
To properly receive bounce notifications from SES, the `Return-Path` header must be set. Since we only have the admin email address, that's what we use for now. Eventually this can be a config.
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/monitor-sending-activity-using-notifications-email.html
=> Set return-path on outgoing emails to ensure bounce notifications

lib/ret_web/router.ex
Hubs Cloud installations have request timeouts going to reticulum of 30s due to the fact that Cloudfront is typically sitting in front of all requests. (This is only the case if the stack is not using an ALB.)
To resolve this, long running requests can be directed to the server directly instead of going through the Cloudfront endpoint. The only API that this seems relevant for is the media resolver + uploader API. This PR updates the API so that it can be hit directly (and won't be redirected to the canonical domain.)
=> Allow direct POSTs to media api

habitat/config/config.toml
A typo in #280 caused google poly api keys to be ignored in hubs cloud instances.
=> Fix config toml for google poly api key

config/prod.exs, lib/ret/db_warmer_job.ex, lib/ret/hub.ex, lib/ret_web/channels/presence.ex
The AWS Aurora database we use for Hubs Cloud shuts down after 5 minutes of no database activity. However, this is problematic when there are people in a room, since it means the next request which uses the database (such as pinning an object) can take up to a minute to complete. As such, this PR sets things up so if there are any CCU in a room on your server the database will stay up.
Additionally, this updates the member count concept to exclude the discord bot, so 'empty' rooms appear as such even if the bot is monitoring them.
=> Add db warmer job, exclude discord from member count

lib/ret_web/channels/hub_channel.ex
It turns out that `handle_out` is quite expensive, given that it always results in N re-encodings of each message, where N is the number of subscribers to the topic. We are using `handle_out` for a variety of purposes, but the vast majority of our messages are `naf` (and now `nafr`) and hence the `handle_out` we are using there specifically leads to a ton of overhead under load.
We use `handle_out` over NAF messages to deal with two concerns:
- If a user is blocked, or is blocking people, we intercept outgoing messages to prevent delivery in both directions.
- If the user has requested (such as in an iframe) to `block_naf` messages overall. In practice, we only do this for hubs which are embedded in iframes - we run with this assumption for now in the interest of optimization.
It turns …
=> Selectively filter packets to reduce reliance upon intercepts

lib/ret_web/channels/auth_channel.ex
I think we should merge this. There's a lot of noise in the sentry logs and I don't know how much of an impact this has on reliability.
=> Add handle_info function for :channel_expired

lib/ret_web/controllers/api/v1/account_controller.ex, lib/ret_web/router.ex, test/ret_web/controllers/api/account_controller_test.exs
Adds a PATCH end point to the accounts API. It accepts the same form of data as the existing POST API and will update the names on one or more accounts. If an account is not found for the email, it returns an error for that record.
=> Add PATCH api for admin account management

lib/ret/hub.ex, lib/ret/media_search.ex, lib/ret_web/channels/hub_channel.ex, lib/ret_web/controllers/api/v1/hub_controller.ex, test/ret_web/controllers/api/hub_controller_test.exs
This PR adds the update route for hubs and the `scene_id` field to hubs views and media search results. This allows us to manage existing rooms via http.
=> Add update hub route

lib/ret/hub.ex, lib/ret/media_search.ex, lib/ret_web/channels/hub_channel.ex, lib/ret_web/controllers/api/v1/hub_controller.ex, test/ret_web/controllers/api/hub_controller_test.exs
Reverts mozilla/reticulum#336
The compiler deadlocked, probably due to some circular dependency. I'm not 100% sure what yet.
=> Revert "Add update hub route"

lib/ret/media_resolver.ex
Sketchfab has updated their model id slugs, so we need to adjust the parsing algorithm.
=> Fix sketchfab model parsing

lib/ret_web/controllers/page_controller.ex
Fixes a fairly severe bug where reticulum CORS proxying was not forwarding the HEAD method properly, because it is re-written to a GET within a phoenix request.
=> Fix bug where cors proxying is not sending HEAD

habitat/plan.sh
Core habitat packages were updated, the latest versions do not exit in our depot, so pinning the versions to the latest stable in our depot for now.
=> Pin package versions in plan.sh

lib/ret/media_resolver.ex
Resolve links like https://www.dropbox.com/s/rds4qdmo5jvzw2l/2020-02-29%2009.23.19-1.jpg?dl=0 to their "raw" form "https://www.dropbox.com/s/rds4qdmo5jvzw2l/2020-02-29%2009.23.19-1.jpg?raw=1" which can be directly loaded through our CORS proxy.
closes #363
=> Better resolving of dropbox urls

lib/ret_web/plugs/add_csp.ex
Add a missing CSP rule needed to snoop for dialog, will be removed after dialog rollout.
=> Add http rule to CSP

lib/ret/media_resolver.ex, lib/ret_web/controllers/api/v1/media_controller.ex
We were previously assuming all resolved youtube urls would have a querystring with expires params, this is not true for live videos. This was previously throwing an error since we tried to call `URI.decode_query` on `nil`, now handling this sort of error as a 500 instead of a 404 and actually returning the error so that we can tell the difference between internal errors and things that actually couldn't be resolved at the source.
Fixes https://github.com/mozilla/hubs/issues/2431
=> Fix resolving of youtube live urls

lib/ret/media_resolver.ex, lib/ret_web/controllers/api/v1/media_controller.ex
This was hitting an error and returning 500, not a big deal but investigated to find out why, and its better explicitly handled than happening to fail.
=> 404 in case where youtube also fails to grab a screenshot

lib/ret/media_resolver.ex
Looks like we can not safely assume content type returned from youtube-dl queries are videos after all. An mp3 still returns a 200 response, but is not recognized as a video. For now just reverting returning of content type. Ideally we would look at the response and be able to decide, but it would need some more work to understand all the possible responses.
fixes https://github.com/mozilla/hubs/issues/2802
=> Don't return content type for youtube-dl queries

lib/ret/enums.ex, lib/ret/hub.ex, lib/ret/hub_invite.ex, lib/ret_web/channels/hub_channel.ex, priv/repo/migrations/20200730155900_add_invite_to_hub_entry_mode_enum.exs, priv/repo/migrations/20200805190647_create_hub_invites_table.exs
Introduces the idea of a `HubInvite`, which allows us to restrict access to rooms when they are in the `:invite` `entry_mode`. Hubs can have multiple invites, but this basic implementation only allows for one. Future enhancements might also include different types of invites, with expiration, usage limits, etc.
Currently, invites do not persist any data on a user's account. They are effectively just used as passwords in this initial implementation. Users must use the invite URL to access an invite-only room.
This PR also adds `hub_channel` handlers to fetch and revoke invites, and room join denial logic to enforce the invites.
=> Basic Hub Invites

lib/ret_web/plugs/admin_only.ex, test/ret_web/controllers/api/account_controller_test.exs
With just put_status, the response that failed on the :admin_only step would receive a 500 response. 
This returns a 402 for unauthorized.
=> Admin only plug returns 401 correctly

lib/ret_web/plugs/add_csp.ex
Add hashes for https://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js and some inline script tags it uses on the doc site.
=> Add CSP rules for docsearch

README.md
The Coturn PSQL connection string needs to explicitly specify the `coturn` schema to be able to connect to the Reticulum DB.
=> Add PosgreSQL config step for a local dialog

lib/ret_web/controllers/api/v1/media_controller.ex
Adds telemetry to media resolution results.
This may be partially redundant with the more specific request types (for example:
```elixir
Statix.increment("ret.media_resolver.poly.requests")
``` 
and
```elixir
Statix.increment("ret.media_resolver.poly.ok")
```
), but still seems useful for monitoring server health.
Note: I don't know how to test this without simply deploying it because it looks like `Statix` is only configured for prod.
=> Add StatsD counters for media resolution results

lib/ret/media_resolver.ex
We frequently get complaints about certain video services not working. In order for us to better understand how frequently users encounter issue this is on HMC, this PR adds a measurement that will increment every time it happens.
=> Add statix measurement of rate_limited responses

lib/ret/http_utils.ex, lib/ret/media_resolver.ex, lib/ret_web/controllers/api/v1/media_controller.ex
Fix https://github.com/mozilla/reticulum/issues/435
=> Fallback to screenshots or opengraph if possible in media resolution

config/dev.exs
`System.get_env("PWD")` was returning an empty string and causing errors when running the dev server. This PR fixes it by using the `File.cwd!` function instead which works cross platform.
=> Fix cert path resolution on non-WSL Windows

lib/ret/scene.ex
Scenes published before Projects were associated with Scenes, and Scenes who's Projects have been deleted should not be considered "projectless" scenes.
=> Exclude scenes with project files from projectless

lib/ret/cached_file.ex
We suspect we may be repeatedly downloading the same assets over and over again as their `CachedFile` records expire. This change extends the lifetime of these records to two days instead of one. We will measure the impact in this change in grafana. This will allow us to (roughly) estimate how many new source URLs are introduced each day and how many are re-requested:
More work is being done to allow the lifetime of `CachedFiles` to be extended until they are no longer used. This change is meant as a quick diagnostic that will be useful in the meantime.
=> Increase CachedFile timeout

lib/ret/media_search.ex
It appears that the Sketchfab API introduced a bug where `processing_status` is no longer accepted. 
Details TBD, but this workaround at least gets most sketchfab searches working again.
More info here: https://discord.com/channels/691604175322087474/700374866720981093/820007295659409429
=> Remove processing_status from sketchfab API query

lib/ret_web/controllers/page_controller.ex
The simplest way to support custom themes for the new UI was to allow users to paste a JSON blob describing an array of themes into the admin panel. In order for this to be parsed correctly by the client, we need to parse the JSON blob into an elixir map in the backend, then re-encode it into the json blob sent to the client.
Client changes are in this PR https://github.com/mozilla/hubs/pull/4109 
The shortcoming of this approach is that it does not do this for all future json configs. I was not sure how to achieve that. Instead, it looks specifically for themes. In order to add more json parameters to the admin panel, we will need to update this code.
=> Add support for setting themes as a json string in app_configs.

priv/repo/migrations/20210416191647_add_session_stats_index.exs
The session_stats table appears to be one of the main bottlenecks for server performance due to the large number of sessions we now handle. The table was created with this in mind, where we partitioned the table in to monthly date ranges, however even this partitioning is not sufficient to mitigate the performance impact it has. This impact is particularly prevalent when we experience a flood of activity, such as when the Hubs Discord Bot needs to reestablish connections for all its bridged rooms.
The majority of the work behind this PR went into testing the performance characteristics of this table. I did so using a number of utility functions to populate a large number of records and test the performance various operations with and without the index. Importantly, while the index does …
=> Add database indexes for the session_stats tables

lib/ret_web/channels/hub_channel.ex
This was particularly a problem with the Discord Bot, where it was attempting to connect to hub channels with hub ids that were either entered incorrectly by the user, or for hubs that had subsequently been deleted from the database. Previously we would error out trying to access `hubs_bindings` of `nil`. This PR changes accounts for a `nil` hub and allows the code to fall through to the corresponding `join_with_hub` overload.
The Discord Bot will look for the `"not_found"` reason and stop attempting to reconnect to this missing hub id with the changes in https://github.com/MozillaReality/hubs-discord-bot/pull/117
=> Properly handle join attempt to non-existent hubs

lib/ret/hub.ex, test/ret/hub_test.exs
This is for usage with "zone audio source" components and any other "presenter" audio features we might add. Still not sure about the name. Originally had `broadcast_audio` but that seems like it might be confused with sending any audio at all. Also considered `present_audio` but that also felt a bit weird.. so I landed on `amplify_audio`. Open to suggestions.
For starters just mirroring the same permission model as `mute_user`. Creators and owners are allowed to do it in unbound rooms, and in bound rooms its tied to `HubBinding.can_moderate_users` which is slightly weird, but we don't really have finer granularity right now.
Don't have an easy way to test room binding locally so I will just test that part in staging. Since I am using the same exact semantics as `mute_user` I think it …
=> Add amplify_audio permission

lib/ret_web/channels/ret_channel.ex
This PR adds a `"change_hub"` event handler to the `"ret"` channel, which we use in https://github.com/mozilla/hubs/pull/4347/commits/6f0506fdcd29a655bbbc98cd76e66ae276cb2dcb (https://github.com/mozilla/hubs/pull/4347)
=> Let clients tell the ret channel they changed hub

lib/ret/media_search.ex
Sketchfab Issue opened: https://forum.sketchfab.com/t/bug-model-search-api-using-max-filesizes-causes-query-to-ignore-categories/40247
=> Removed max_filesizes query param due to sketchfab bug

config/dev.exs
We introduced a storage host configuration in #508 but neglected to add it to the dev config.
Fixes #522
=> Fix dev storage host configuration

lib/ret/discord_client.ex, lib/ret/http_utils.ex, lib/ret/media_resolver.ex, lib/ret/media_search.ex, lib/ret/slack_client.ex, lib/ret/speelycaptor.ex, lib/ret/twitter_client.ex
In #452 we added a browser user-agent header to all requests made through all the functions in our HttpUtils module. That change is now breaking Discord integration, since it seems Discord now rejects API requests that include a user-agent header.
This PR removes the user-agent header from all requests by default, unless it is enabled with the new `append_browser_ua` parameter. Incidentally, the functions in HttpUtils have also been changed to use a keyword-list for their optional parameters, to avoid having to worry about positional arguments.
As far as I can tell, only the screenshot and opengraph code paths require a user-agent header enabled, so I've had all the other calls omit the header by default.
=> Fix Discord integration

lib/ret/http_utils.ex, mix.exs, mix.lock, test/ret/http_utils_test.exs, test/support/test_helpers.ex
A regression introduced in #531 broke the asset import feature in the admin panel. The function signature for `retry_head_then_get_until_success` was changed, but the call site in `fetch_content_type` was not changed accordingly.
This PR fixes `fetch_content_type` and also adds a test that uses the Mox library to exercise the function with a basic test.
=> Fix asset import helper

lib/ret/twitter_client.ex, lib/ret_web/channels/hub_channel.ex
If twitter is misconfigured, either with a typo in the tokens configured, or a configuration error in the twitter developer console, it may result in API calls failing in reticulum. Previously, this would cause the hub_channel websocket to crash, and break the client in different ways (perhaps causing the game loop to stop). 
This PR adds error handling so that we forward the error to the client, instead of crashing entirely.
Goes with https://github.com/mozilla/hubs/pull/4997
=> Respond with an error if twitter might be misconfigured

lib/ret_web/controllers/file_controller.ex
Account for Hubs Cloud stacks with Cloudflare CDN enabled. Instead of checking the host header against the configured storage host, we need to use the cf-worker header and check that it matches the suffix of the configured host.
=> Hubs Cloud Cloudflare uploads fix

lib/ret_web/plugs/add_csp.ex
Troika text loads fonts using fetch not directly as a CSS font so this needs to be in our connect-src as well (it was previously already in our font-src for use in CSS)
=> Add fonts.gstattic.com to connect-src for Troika

lib/ret_web/plugs/add_csp.ex
Troika Text library needs some additional CSP rules for its workers to load correctly.
=> Fix CSP for troika-text

config/dev.exs, habitat/config/config.toml, lib/ret/application.ex, lib/ret_web/controllers/api/v1/whats_new_controller.ex, lib/ret_web/router.ex
This replaces client code that previously used the Github API directly in the client code. This allows us to keep the github token safe, and affords us some caching. It also uses Github's GraphQL API instead of their REST API, which is a bit more efficient.
Goes with:
- https://github.com/mozilla/hubs/pull/5126
- https://github.com/mozilla/Spoke/pull/1221
- https://github.com/mozilla/hubs-ops/pull/155
=> Add new whats-new API to query GitHub for merged pull requests

priv/repo/migrations/20220304230943_add_hubs_public_rooms_index.exs
Querying for public rooms can put a lot of load on the DB. This index helps with that considerably.
Here is the process I used for measuring the perf:
1. Use [Apache Bench](https://httpd.apache.org/docs/2.4/programs/ab.html) to measure baseline perf:
`ab -c 50 -n 500 'https://hubs.local:4000/api/v1/media/search?source=rooms&filter=public&cursor=0'`
3. Create 20,000 rooms:
`1..20000 |> Enum.each(fn _ -> Ret.Hub.create_new_room(%{"name" => "foo"}, true) end); `
4. Run benchmark again to measure perf after the migration adds the index.
=> Optimize public rooms queries

lib/ret_web/channels/hub_channel.ex
This PR adds support for typing and hand raised states updates in Reticulum.
Hubs client related PR: https://github.com/mozilla/hubs/pull/5195
=> New name tags typing and raised hand support

config/turkey.exs, lib/ret_web/controllers/api-internal/v1/presence_controller.ex, lib/ret_web/router.ex
To ensure the internal endpoints are private and secure, organize the endpoint under /api-internal/v1 and NOT /api/v1.
=> Portal/internal endpoints /v1/internal -> /api-internal/v1

lib/ret_web/plugs/add_csp.ex
Previously, we added an IE-specific CSP header to prevent script execution in file uploads. However, the stricter CSP was also applied to page URLs, which broke the front page as well. 
This relaxes the CSP logic, so that the additional header is only used when the AddCSP plug is configured to be strict.
=> Fix over-aggressive CSP for IE11

lib/ret/storage_used.ex
`Df` doesn't work because of the combination of how `df` works and the container mounting in gcs. Use `du` instead for turkey.
=> Use `du` storage command for turkey instead of `df`

lib/ret_web/plugs/add_csp.ex
This change allows Hubs Client to play recorded camera video in a new tab by clicking "Open Link" on the object menu.
See https://github.com/mozilla/hubs/issues/5576
=> Add media-src CSP

config/test.exs, lib/ret/account.ex, lib/ret/project.ex, lib/ret/scene.ex, lib/ret/storage.ex, test/ret/project_test.exs, test/ret/scene_test.exs, test/support/dummy_data.ex, test/support/test_helpers.ex
Amend the asset rewrite implementations so that they immediately delete old assets, instead of waiting for them to be demoted and vacuumed.
Also adds tests to cover existing assets rewrite code, and verify the deletion of old assets.
=> Amend asset rewrite implementation 

lib/ret/load_balancing/janus_load_status.ex
dialog's port 7000 in turkey arch is internal and only used to report local levels
=> get_dialog-pod fixes for turkeymode

bin/README.md, bin/iex, bin/mix, bin/psql, config/config.exs, config/dev.exs, lib/ret_web/plugs/proxies.ex
Why
---
Content administration screens cannot load and the following error messages appear in the browser when Hubs is orchestrated with Docker Compose:
* Missing file index.html. Please try again.
* Missing file admin.html. Please try again.
Reticulum is run against an external Dialog instance.  I want to be able to tweak, and thus run against, a local instance.
I want to be able to easily run common commands inside the orchestrated container from my own shell.
What
----
* Allow hostnames for the following to be supplied by OS vars:
+ hubs client
+ hubs admin
+ postgREST
+ spoke
+ dialog
* Add `bin/iex`, `bin/mix`, and `bin/psql`
=> Prepare for local orchestration

lib/ret/hub.ex
Currently in Discord bound rooms only moderators can text/voice chat, regardless of the room permission setting. This clause will always match when checking for voice/text chat permission and only checks if a user is a moderator. We want this check to fall through to the next clause where moderators are always allowed, and normal users are checked against the room permission.
Testing this locally is pretty tricky so I haven't actually tested this fix...
=> Fix non-mods unable to chat in bound rooms

bin/iex, bin/mix, bin/psql
Why
---
I want to be able to run tasks under the test environment inside the container
as I would locally.  For instance $ `MIX_ENV=test mix ecto.reset` has the
desired effect, but $ `MIX_ENV=test bin/mix ecto.reset` does not.
When the path contains a space all of the scripts break.  This is because the
commands treat the path as multiple arguments.
What
----
* Update `bin/mix` and `bin/iex` to pass `$MIX_ENV` through to the container
* Quote paths
=> Update container scripts

.github/workflows/lint-and-test.yml
Why
---
Our `ubuntu-latest` changed from `ubuntu-20.04` to `ubuntu-22.04` which
does not support OTP 22
What
----
Pin to lint-and-test to Ubuntu 20.04
=> Fix GitHub lint-and-test action

lib/ret/storage_used.ex
Fix a bug related to estimating disk use.
Explanation of the `-P` flag:
> This is like the default format except that the information about each filesystem is always printed on exactly one line; a mount device is never put on a line by itself. This means that if the mount device name is more than 20 characters long (e.g., for some network mounts), the columns are misaligned.
> 
> https://www.math.utah.edu/docs/info/fileutils_8.html
Without this flag, we fail to parse the output correctly with long device names. e.g.
```elixir
iex(1)> System.cmd("df", ["-k", "storage/dev"])
{"Filesystem           1K-blocks      Used Available Use% Mounted on\n/dev/mapper/MyVolGroup-root\n                      65478188  55206600   6899764  89% /code\n",
0}
```
Notice the trailing newline after …
=> Use POSIX output format with df

.github/workflows/hc-pkgcaller.yml
This adds a workflow to move the branch pointer and tag the new releases.
=> Adding new workflow to move branch pointers for post release chore. 

lib/ret/repo/migration_helpers.ex, priv/repo/migrations/20230105144400_create_node_stats_partitions_through_2030.exs, priv/repo/migrations/20230105144433_create_session_stats_partitions_through_2030.exs, test/ret/repo/migration_helpers_test.exs, test/ret/schema_test.exs
Why
---
The `node_stats` table was only partitioned through 2022.  While the `session_stats` table was partitioned through 2030, an earlier released version of the migration only partitioned the table through 2022.
What
----
* Create migration to create `node_stats` partitions through 2030
* Create migration to create `session_stats` partitions through 2030
* Fix `StreamData.TooManyDuplicatesError` intermittent test failure
Note
----
If any partitions have already been created, they will be skipped during partition creation
=> Fix missing stats partitions

priv/repo/migrations/20230104213552_grant_admin_delete_on_projects.exs
Why
---
When I attempt to delete a project from the admin panel, a 403 status is returned, the project remains, and I am redirected to the login page
What
----
Create a database migration to grant admin permissions to `ret_admin` to delete records from the `ret0_admin.projects` view
=> Fix admin project deletion

TurkeyDockerfile
Why
---
The Elixir upgrade was only meant to upgrade the Elixir version and not the Erlang version.  When the Elixir version was bumped for clustered instances, the Erlang version was implicitly bumped.  This led to `UndefinedFunctionError` exceptions being raised for functions that were fully deprecated in OTP 24.
What
----
* Declare the Erlang version
* Declare the Alpine version
* Declare the precise Elixir version
=> Fix UndefinedFunctionError on clustered instances

lib/ret/media_resolver.ex
If `retry_get_until_valid_ytdl_response` fails, it seems to return `:error`. This adds a case clause to catch this possibility so that execution can continue normally after `fetch_ytdl_response`.
=> Add missing case for failed resolution from youtube-dl

lib/ret_web/controllers/api/v1/media_controller.ex, lib/ret_web/controllers/page_controller.ex
problem:
in turkey arch, reticulum is hosted behind ingress controller.
the ingress controller terminates TLS connection for reticulum, so the connection observed by reticulum is http instead of https, this will fail the is_cors_proxy_url check
solution:
- TURKEY_MODE switch
- uses the "de-facto standard" x-forwarded-proto header set at ingress to determine
- no change on host name check
- skip port# check
=> update is_cors_proxy_url check to enable cors_proxy when hosted behind proxy

lib/ret/media_resolver.ex
Reduce the number of attempts to fetch a URL from ytdl, and expire the retry loop faster.
If ytdl is returning some unexpected error that causes us to retry, then we might be making more requests than is necessary. This protects against that case.
**edit**
I'm not sure that this PR meaningfully improves the situation. I need to measure whether resolving media causes many retries or not. If what's _actually_ happening is that media resolution hangs until the 7 or 15 second timeout, then this change is not helpful or necessary.
=> Reduce number of ytdl retries and expire faster

lib/ret/hub.ex, lib/ret_web/channels/hub_channel.ex
If a client causes a room's `host` to change, broadcast the change so that other clients in the room are notified of this change and can migrate their connections to the new dialog host.
https://github.com/mozilla/hubs/pull/5975
=> Broadcast host_changed events when hub.host changes

lib/ret/load_balancing/janus_load_status.ex
We have observed get_dialog_pods/0 fail to discover dialog nodes within the cluster for reasons we don't yet fully understand. In the meantime, the simplest "fix" is to prefer stale cache data instead of overwrite it.
The :ignore atom is meant to tell Cachex not to update the cache.
Since this warmer runs every 15 seconds, we think an occasional intermittent failure will not cause major issues.
=> Prefer stale dialog pod data to invalid results

lib/ret/random_room_names.ex
1/2 of the resolution of https://github.com/mozilla/hubs/issues/6283. Good idea to remove this from the wordlist.
The second half of this issue is resolved with this PR: https://github.com/mozilla/hubs/pull/6284
=> Remove 'crazy' from the random Hubs room name generation wordlist

.github/workflows/ret-turkey.yml
Use the Hubs Foundation's docker hub repository for building and pushing docker images.
=> Hubs Foundation docker registry update

.github/workflows/ret-turkey.yml
It was decided that continuing to use ret is too obscure and that now is the time to change it before too much history builds up.
Corresponding change for the Community Edition: https://github.com/Hubs-Foundation/hubs-cloud/pull/366
=> Use reticulum as the docker repository instead of ret

lib/ret_web/templates/page/hub-meta.html.eex
Checks that scene is truthy before extracting scene name for metadata
If the scene is falsy, this error arises:
```
key :name not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
```
Apparantly, the scene can be nil, at least in hubs-compose, some of the time
Without this check, reticulum can't generate the HTML for the room
1.     run the down script
2.     cd to reticulum in hubs-compose
3.     pull this branch
4.     run the up script
6.     open a Hubs room
7.     use the browser console to verify the JSON-LD metadata is there. `disambiguatingDescription` may be zero-length.
This PR doesn't update the lint-and-test GitOps
It's unclear if there's a more idiomatic way that works in an Elixir template
=> fixes bug: HTML for room generated even if scene is nil

.github/workflows/lint-and-test.yml
Updates Ubuntu for building to supported, and checkout action to current.
The proximal cause was GitOps lint-and-test being blocked for building using an old version of Ubuntu.
I. GitOps lint-and-test Action should fail only due to warnings being treated as errors
II. GitOps turkeyGitops Action should succeed (when running in the HubsFoundation repo)
III. hubs-compose with this should build and not have regressions
1. run the down script
2. cd to reticulum in hubs-compose
3. pull this branch
4. run `mix deps.get`
5. run the up script
6. if the reticulum container builds successfully, the Elixir automated tests have passed
7. smoke test Hubs
no changes
This PR doesn't update Elixir, which will need more testing.
=> Updates GitOps 

.github/workflows/lint-and-test.yml, .github/workflows/ret-turkey.yml, TurkeyDockerfile, mix.lock
Updates Elixir and Erlang/OTP to latest that pass tests
The proximal cause was GitOps lint-and-test being blocked for building using an old version of Ubuntu.
As we need to test for regressions, it made sense to update what else we can.
I. GitOps lint-and-test Action should succed for Elixir 1.16 and Erlang/OTP 25.3 (the versions in turkeyDockerfile)
II. GitOps turkeyGitops Action should succeed (when running in the HubsFoundation repo)
III. hubs-compose with this should build and not have regressions
1. run the `down` script
2. cd to reticulum in hubs-compose
3. pull this branch
4. run `mix deps.get`
5. run the `up` script
6. if the reticulum container builds successfully, the Elixir automated tests have passed
7. when all containers are running, smoke test Hubs
(This is currently …
=> Updates Elixir, Erlang OTP, Alpine & GitOps

.github/workflows/ret-turkey.yml
Only builds images when the master branch on the Hubs-Foundatioin fork changes
* avoids doomed attempts to run in forked repos
* avoids publishing from non-master branches
1. push to master in forked repo
2. observe that action is kicked off, but job turkeyGitops doesn't run
3. push to non-master branch in original repo
4. observe that the action is not kicked off
Avoids failed runs; no new functionality
=> turkeyGitops only run on push to master in Hubs-Foundation

lib/ret/http_utils.ex, lib/ret_web/controllers/file_controller.ex, lib/ret_web/controllers/page_controller.ex, lib/ret_web/email.ex, lib/ret_web/templates/file/show.html.eex, lib/ret_web/templates/page/avatar-meta.html.eex, lib/ret_web/templates/page/hub-meta.html.eex, lib/ret_web/templates/page/hub.service-meta.js.eex, lib/ret_web/templates/page/index-meta.html.eex, lib/ret_web/templates/page/link-meta.html.eex, lib/ret_web/templates/page/scene-meta.html.eex, lib/ret_web/templates/page/whats-new-meta.html.eex
Provides default values and fallback values when admin hasn't set an App Setting or the code doesn't currently supply it.
Assembles the available values so there are no unprofessional-looking gaps.
* For a room, if scene is nil, uses scenelist
* Provides context text, so social media previews are actionable
* If App Name is nil, uses hostname
* if Company Name is blank, uses App Name
* forms descriptions using all relevant values, eliminating nils and concatenating values using em-dashes
Admins don't necessarily set all the App Settings.
There are bugs, such as the scene being unavailable for some rooms.
Metadata such as titles and descriptions is often the first contact a user has with an instance. If they contain obvious gaps, the instance looks amateurish.
1. Pull this branch into Hubs …
=> Assembles informative & polished metadata from whatever values are available

lib/ret/discord_client.ex
If no per-server nickname has been set, this checks to see if Discord's global name is set for the user before falling back to the username.
This makes the name used in Hubs match what Discord displays in the Discord server instead of predominantly using their (usually less aesthetically pleasing) username.
N/A
1. Redeploy your instance using a Reticulum image generated from this PR (e.g. `ghcr.io/exairnous/reticulum:use-discord-display-names-37`). 
2. Follow the instructions for hacking on the bot locally that are listed in PR https://github.com/Hubs-Foundation/hubs-discord-bot/pull/146 and set up the Hubs bot against your Community Edition instance.
3. Create a room with the Hubs bot with `!hubs create`.
4. Join the room created by the Hubs bot.
5. See that your username is …
=> Check for the global name if the per-server nickname isn't present

lib/ret/discord_client.ex
Fixes a bug with getting the permissions of users for Discord bound rooms.  The permissions for the roles a user has weren't getting combined into a single bitfield correctly and instead it seemed that the permissions for just one of the roles was being picked (which may or may not give them all the powers they are supposed to have).  This explicitly specifies the order of operations so that everything gets combined correctly.
Users weren't always given the powers they should have been based on their Discord roles, which could prevent moderators and admins from being able to kick users and edit room settings.
1. Load/Create a Discord bound room from a Discord server where you aren't the owner, but have roles that give you either the ability to kick people or manage channels, on a Hubs …
=> Fix user permissions bug for Discord bound rooms

lib/ret/storage_used.ex
Changes the format string that is passed to the io_lib.fread function from a binary/UTF-8 encoded string back to a character list, but uses the character list sigil syntax, rather than single quotes, to make `mix format` happy.
Hubs Compose throws errors when io_lib.fread is passed a binary/UTF-8 encoded string, rather than a character list.
N/A
1. Run this PR using Hubs Compose.
2. See that Hubs Compose now works.  Previously, Reticulum would fail to start in Hubs Compose and complain of `fread` errors in the logs (specifically: `** (FunctionClauseError) no function clause matching in :io_lib_fread.fread/4`).
3. Deploy this PR to a Hubs Community Edition instance.
4. See that the instance continues to function normally.
This PR doesn't add, remove, or change the behavior of any Hubs …
=> Switch fread in storage_used.ex back to using a character list
