README.md
---
<sub><b>this pr does basically aim at:</b></sub>
- <sub><i>adding title to readme.md file</i></sub>
- <sub><i>adding thumbnail title to readme.md file</i></sub>
- <sub><i>styling up the document</i></sub>
---
<sub><b>Let's make the web better bit by bit</b></sub>
<sub><b>Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.</b></sub>
---
=> [Docs] README.md - heading; thumbnail

Jenkinsfile
Commit authors like "Dominick D'Aniello" were breaking the script because of the single quote.
=> Escape git author and commit messages in shell script

Jenkinsfile, habitat/plan.sh
Makes the asset bundle server configurable in the client
=> Set ASSET_BUNDLE_SERVER env var

lib/ret_web/router.ex
🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆 🦆
=> "Given enough thrust, pigs can fly"

lib/ret/media_resolver.ex
Refactoring into pipelines, remove some ytdl sites for now.
=> Remove some sites for now, refactor resolver

lib/ret_web/controllers/page_controller.ex
Goes with https://github.com/mozilla/hubs/pull/570
=> Render scenes with the index page

lib/ret/page_origin_warmer.ex, lib/ret_web/controllers/page_controller.ex, lib/ret_web/templates/page/hub-meta.html.eex, lib/ret_web/templates/page/scene-meta.html.eex
Adds scene pages, dependent upon https://github.com/mozilla/hubs/pull/592
=> Add scene page

lib/ret/support.ex, lib/ret_web/controllers/api/v1/scene_controller.ex
Posts new and updated scenes to slack
=> Add slack notification for new scenes

lib/ret_web/controllers/file_controller.ex, lib/ret_web/router.ex, lib/ret_web/templates/file/show.html.eex, lib/ret_web/views/file_view.ex
This adds a simple landing page for uploaded photos, primarily just to add metatags for sharing on twitter.
=> Add simple landing page for uploaded photos

lib/ret_web/controllers/page_controller.ex
Fix for https://sentry.prod.mozaws.net/operations/reticulum/issues/4926660/?query=is:unresolved
=> Fix for bad scene filter

lib/ret_web/views/api/v1/hub_view.ex, lib/ret_web/views/api/v1/scene_view.ex
This PR adds the scene information, if any, to the hubs JSON payload (so it can be used to show the scene information in the room page.)
=> Add scene information to Hubs API

lib/ret_web/channels/hub_channel.ex, lib/ret_web/controllers/api/v1/scene_controller.ex, lib/ret_web/views/api/v1/scene_view.ex
Adds the .spoke file in API responses for re-mixable Spoke scenes.
=> Render scene owned file

test/ret_web/controllers/api/project_assets_controller_test.exs, test/support/test_helpers.ex
Fixes a few regressions in the project assets tests
=> Fix project asset tests

lib/ret/discord_client.ex, lib/ret/hub.ex, lib/ret/hub_binding.ex, lib/ret/perms_token.ex, lib/ret_web/channels/hub_channel.ex, lib/ret_web/controllers/api/v1/oauth_controller.ex, test/ret/discord_client_test.exs
Refactor and generalize permissions checks. Add permissions based on discord permissions.
=> Discord permission mappings

lib/ret_web/controllers/api/v1/avatar_controller.ex
This is to help diagnose issues with avatar updating, and is also just the polite thing to do. These technically should be json responses, but we don't do that anywhere else yet so this doesn't seem like the place to start.
=> Add better responses to avatar 401s

config/dev.exs, config/prod.exs, config/test.exs, habitat/config/config.toml, lib/ret_web/add_csp_plug.ex, lib/ret_web/router.ex, mix.exs, mix.lock
Also uses phoenix-native plug for adding security headers.
=> Write custom plug to add CSP

lib/ret_web/channels/auth_channel.ex
This updates the auth channel protocol to also broadcast out the email address from the originating request after the token is verified, so the page which is verifying can also be logged in.
=> Broadcast email over auth channel after token verified

config/dev.exs, lib/ret/page_origin_warmer.ex, lib/ret_web/channels/hub_channel.ex, lib/ret_web/controllers/page_controller.ex
Adds bits to presence to support streamer mode (and eventually camera recording)
=> Add streaming and recording flags to presence

config/dev.exs, lib/ret/http_utils.ex, lib/ret/media_resolver.ex
This fixes a bunch of issues with uploaded file media resolution when testing the full stack locally. This code was already reviewed in the photo sharing PR.
=> Fix up local file resolution

lib/ret/hub.ex
Not sure how we never caught this until now
=> Fix for scene listing thumbnails

lib/ret_web/channels/hub_channel.ex
Persistent first syncs don't need to be authorized, since they should not result in instantiated entities.
=> Do not authorize persistent first syncs

lib/ret_web/channels/hub_channel.ex
Adds bi-directional blocking of NAF and chat messages for avatars which have been blocked/hidden by a user. 
Hubs PR: https://github.com/mozilla/hubs/pull/1585
=> Adds proper message filtering of blocked avatars

lib/ret/hub.ex, lib/ret_web/channels/hub_channel.ex
- Broadcasts user permissions in presence.
- Removes server side authorization and state related to NAF remove messages in favor of client authorization.
=> Client-side update authorization

lib/ret/avatar.ex
Previously we only ever had a single depth of avatar:
Avatar A -> Base
Now with remixing you can have arbitrary depth:
Avatar B -> Avatar A -> Base
This restores the original recursion we dropped when introducing listings since it is again required. Also, none of our avatars actually use the `parent_avatar` chain, so starting the phase it out.
=> Fix fetching gltf for avatars with a chain of parents

lib/ret/avatar.ex
The mc avatars apparently use parent_avatar so we have to keep supporting that. Code is ugly but just trying to fix things at the moment.
=> Fix parent_avatar usage for mc avatars

lib/ret/media_search.ex
This should give better results than just including things that share the target's parent
=> Include target avatar, and its children in similar

config/prod.exs, habitat/config/config.toml, habitat/default.toml, lib/ret_web/plugs/redirect_to_main_domain.ex
Adds an additional host that will avoid redirects when hitting reticulum, needed for self hosting.
=> Add secondary host

habitat/config/config.toml, habitat/default.toml, lib/ret/application.ex, lib/ret/cached_file.ex, lib/ret/meta.ex, lib/ret/storage.ex, lib/ret/storage_used.ex, lib/ret_web/controllers/api/v1/media_controller.ex
Adds the `quota_gb` config which will block subsequent attempts to store files if the disk the storage path is on has more than `quota_gb` GB in-use.
=> Added disk quota

lib/ret/app_config.ex, lib/ret/page_origin_warmer.ex, lib/ret_web/controllers/file_controller.ex, lib/ret_web/controllers/page_controller.ex, lib/ret_web/email.ex, lib/ret_web/endpoint.ex, lib/ret_web/templates/file/show.html.eex, lib/ret_web/templates/page/avatar-meta.html.eex, lib/ret_web/templates/page/hub-meta.html.eex, lib/ret_web/templates/page/hub.service-meta.js.eex, lib/ret_web/templates/page/index-meta.html.eex, lib/ret_web/templates/page/link-meta.html.eex, lib/ret_web/templates/page/scene-meta.html.eex, lib/ret_web/templates/page/spoke-index-meta.html.eex, lib/ret_web/templates/page/whats-new-meta.html.eex
- Configurable meta tags and titles in entry pages
- Injected app name into hub.service.js
- Parameterized email content
- Removed unused spoke image assets
- Removed static fallback for app icons and thumbnail. They must be configured in the DB now.
- Removed old spoke landing page
=> Configurable meta tags, etc.

lib/ret_web/controllers/api/v1/project_controller.ex, test/ret_web/controllers/api/projects_controller_test.exs
New project endpoint was missing slack notifications.
=> Send notification to slack on project publish

lib/ret_web/plugs/proxies.ex, lib/ret_web/router.ex
=> Add docs proxy

lib/ret/media_search.ex
Required to show edit buttons on "My Scenes"
=> Expose project id on scene search results

lib/ret/project.ex
Projects now sort by last updated in descending order.
=> Fix projects sort order

lib/ret/media_resolver.ex
Attempt to fix https://github.com/mozilla/hubs/issues/1936
Vimeo resolves to `mpd` files using our current ytdl format rules, this PR updates specific sites to prefer HLS playlists. For vimeo, if we just preferred mp4 and forced non-mpd, those URL ultimately fail to load, so HLS is necessary.
=> Disable MPD, force hls on some sites

lib/ret/media_resolver.ex
=> Revert "Disable MPD, force hls on some sites"

lib/ret/hub.ex, lib/ret/media_search.ex, lib/ret_web/channels/hub_channel.ex, lib/ret_web/views/api/v1/hub_view.ex, priv/repo/migrations/20200212220224_add_description_to_rooms.exs
Adds description to rooms. Can be modified by users with the `update_hub` permission.
Hubs changes: https://github.com/mozilla/hubs/pull/2137
=> Add description to rooms

lib/ret_web/channels/hub_channel.ex
Server profiling revealed the cost of JSON parsing all the NAF messages is significantly expensive under load. Since the server only cares about `isFirstSync` messages, this PR adds a new `nafr` ("NAF Raw") message type that can be used to bypass message parsing. The server will pass through any NAF messages sent over this event that do not contain the string `isFirstSync`, and as such are known to be non-server-authoratative. On the client, the contract is that these messages contain a stringified JSON payload under the key `naf`, that contains the data we normally would have passed as-is to phoenix. The net effect is that the messages are still delivered but are not parsed along the way on the server.
For convenience, if the client happens to pass a message through that does contain …
=> Add nafr messages

lib/ret/hub.ex, lib/ret/media_search.ex, lib/ret_web/channels/hub_channel.ex, lib/ret_web/controllers/api/v1/hub_controller.ex, test/ret_web/controllers/api/hub_controller_test.exs
Now with less deadlocks! (hopefully)
I had Elixir 1.9.4 installed locally and didn't see deadlocks until the build on CI which is running Elixir 1.8.0. We should probably update Elixir on CI/prod once things settle down.
=> Update Hub Route

lib/ret/hub.ex, priv/repo/migrations/20200313232157_add_fly_permission.exs
see: https://github.com/mozilla/hubs/pull/2224
=> add flying to member_permissions

lib/ret/media_resolver.ex
=> Revert "Fix sketchfab model parsing"

lib/ret/media_resolver.ex
Increase Google Poly rate limit to 1k/min
=> Increase Google Poly Rate Limit

config/dev.exs, habitat/config/config.toml, priv/repo/migrations/20200413202224_add_coturn_schema.exs
Updates the (already run in HMC) migration to also create a coturn user, which is necessary for the hubs cloud deployment of TURN.
=> Add coturn user create

lib/ret_web/controllers/page_controller.ex
Needed for https://github.com/mozilla/hubs/pull/2460
=> Add signin and verify pages

lib/ret/media_search.ex, test/ret_web/controllers/api/media_search_controller_test.exs
Fixes https://github.com/mozilla/hubs/issues/2148
=> Do not show favorite rooms that have been closed

lib/ret_web/plugs/add_csp.ex
Added CSP rules due to guide: https://developers.google.com/tag-manager/web/csp#universal_analytics_google_analytics
Fixes: mozilla/hubs-cloud#117
=> Added csp for google analytics

habitat/config/config.toml, lib/ret_web/email.ex
Added ability to customize email subject + email message for magic link login emails.
=> Able to customize magic link login email message + subject from admin panel

lib/ret_web/plugs/add_csp.ex
=> Removed csp parsing error https://:port number for HC and HMC

Jenkinsfile, README.md, lib/ret_web/plugs/add_csp.ex
- #418 - Able to customize magic link login email message + subject from admin panel
- #428 - Removed csp parsing error https://:port number for HC and HMC
=> Hubs Cloud QA Update 2021-01-07

Jenkinsfile, README.md, lib/ret_web/email.ex, lib/ret_web/plugs/add_csp.ex
- #418 - Able to customize magic link login email message + subject from admin panel
- #428 - Removed csp parsing error https://:port number for HC and HMC
=> Hubs Cloud Update 2021-02-02

config/config.exs, config/dev.exs, config/test.exs, habitat/default.toml
Add comments to dev configs so that they are not mistaken as real values.
=> Add comments to dev configs

lib/ret/cached_file.ex
Followup of https://github.com/mozilla/reticulum/pull/481 and https://github.com/mozilla/reticulum/pull/480
=> Extend CachedFile lifetime

lib/ret_web/controllers/page_controller.ex
Add support for custom UI themes
=> April hubs cloud release themes update

lib/ret_web/views/api/v1/scene_view.ex
fixes mozilla/Spoke/issues/1134
=> Don't return null for deleted projectless scenes

README.md
Minor updates to setup instructions.
=> Update readme setup instructions

config/test.exs, lib/ret_web/controllers/file_controller.ex, test/ret_web/controllers/file_controller_test.exs
=> Revert "Upload domain fix"

config/test.exs, lib/ret_web/controllers/file_controller.ex, test/ret_web/controllers/file_controller_test.exs
=> Revert "Revert "Upload domain fix""

README.md
Updated readme to reflect the limitation of local install.
=> updated readme to reflect issues with local install

config/dev.exs, lib/ret_web/channels/presence.ex, lib/ret_web/controllers/api/v1/presence_controller.ex, lib/ret_web/plugs/portal_header_authorization.ex, lib/ret_web/router.ex
CCU presence endpoint added. Secured by header.
Ghosts are included in the presence count.
=> Added presence endpoint for CCU across rooms

rel/config.toml
tested on https://g2.dev.myhubs.net/
=> Add sketchfab api key config

README.md, config/dev.exs, config/turkey.exs, lib/ret_web/plugs/portal_header_authorization.ex, lib/ret_web/router.ex, rel/config.toml
Changes `Portal` to `Dashboard`
Changes README from admin portal to admin panel
Will merge https://github.com/mozilla/reticulum/pull/580 first
Then will update this PR to reflect that.
=> portal -> dashboard

lib/ret_web/controllers/page_controller.ex
resp http 200 for kube-probe and 404 for everything else
=> better room_id not found response

.github/workflows/ret-turkey.yml
Removed personal_ from two variables.
=> set variables to be aligned with other actions

lib/ret/hub.ex
In #688 I changed the return type of `ensure_hub` on accident.
=> hotfix PR #688

lib/ret/media_search.ex
=> Revert "Add a search query for owned rooms"
